ManagerSales-MVC/ManagerSales.Web.GUI/Models/ManagerSalesModels/Sale.cs
using System;

namespace ManagerSales.Web.GUI.Models.ManagerSalesModels
{
    public class Sale
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Summ { get; set; }
        public Customer Customer { get; set; }
        public Manager Manager { get; set; }
        public Product Product { get; set; }
    }
}

ManagerSales-MVC/ManagerSales.Web.GUI/Models/Sale.cs
using System;

namespace ManagerSales.Web.GUI.Models
{
    public class Sale
    {
        public int Id { get; set; }
        public string ManagerName { get; set; }
        public DateTime Date { get; set; }
        public string CustomerName { get; set; }
        public string ProductName { get; set; }
        public double Summ { get; set; }
    }
}

ManagerSales-MVC/ManagerSales.Web.GUI/Controllers/GraphicController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using ManagerSales.BL.Models;
using ManagerSales.BL.ModelsHandlers;
using ManagerSales.BL.ModelsHandlers.Intarfaces;

namespace ManagerSales.Web.GUI.Controllers
{
    public class GraphicController : Controller
    {
        private readonly IModelHandler<Manager> _managerHandler;
        private readonly IModelHandler<Product> _productHandler;
        private readonly IModelHandler<Sale> _saleHandler;

        public GraphicController()
        {
            _saleHandler = new SaleModelHandler();
            _managerHandler = new ManagerModelHandler();
            _productHandler = new ProductModelHandler();

            Mapper.CreateMap<Customer, Models.ManagerSalesModels.Customer>();
            Mapper.CreateMap<Product, Models.ManagerSalesModels.Product>();
            Mapper.CreateMap<Manager, Models.ManagerSalesModels.Manager>();
            Mapper.CreateMap<Sale, Models.ManagerSalesModels.Sale>();
        }

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetJsonForProductGraphic()
        {
            var sales =
                Mapper.Map<IEnumerable<Sale>, IEnumerable<Models.ManagerSalesModels.Sale>>(
                    _saleHandler.GetAll());

            var products =
                Mapper.Map<IEnumerable<Product>, IEnumerable<Models.ManagerSalesModels.Product>>(
                    _productHandler.GetAll());

            var dict = new
            {
                name = "Products",
                colorByPoint = true,
                data = products
                    .Select(x => new {name = x.Name, y = sales.Count(y => y.Product.Id == x.Id)})
                    .ToArray()
            };

            var array = new object[] {dict};

            return Json(array, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetJsonForManagerGraphic()
        {
            var sales =
                Mapper.Map<IEnumerable<Sale>, IEnumerable<Models.ManagerSalesModels.Sale>>(
                    _saleHandler.GetAll());

            var salesNumber = (double) sales.Count()/100;

            var managers =
                Mapper.Map<IEnumerable<Manager>, IEnumerable<Models.ManagerSalesModels.Manager>>(
                    _managerHandler.GetAll());

            var dict = new
            {
                name = "Managers",
                colorByPoint = true,
                data = managers
                    .Select(
                        x =>
                            new
                            {
                                name = x.LastName,
                                y = salesNumber != 0 ? (double) sales.Count(y => y.Manager.Id == x.Id)/salesNumber : 0,
                                drilldown = x.LastName
                            })
                    .ToArray()
            };

            var array = new object[] {dict};

            return Json(array, JsonRequestBehavior.AllowGet);
        }
    }
}

ManagerSales-MVC/ManagerSales.Web.GUI/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using ManagerSales.BL.Models;
using ManagerSales.BL.ModelsHandlers;
using ManagerSales.BL.ModelsHandlers.Intarfaces;

namespace ManagerSales.Web.GUI.Controllers
{
    public class SaleController : Controller
    {
        private readonly IModelHandler<Customer> _customerHandler;
        private readonly IModelHandler<Manager> _managerHandler;
        private readonly IModelHandler<Product> _productHandler;
        private readonly IModelHandler<Sale> _saleHandler;

        public SaleController()
        {
            _saleHandler = new SaleModelHandler();
            _customerHandler = new CustomerModelHandler();
            _managerHandler = new ManagerModelHandler();
            _productHandler = new ProductModelHandler();

            Mapper.CreateMap<Customer, Models.ManagerSalesModels.Customer>();
            Mapper.CreateMap<Product, Models.ManagerSalesModels.Product>();
            Mapper.CreateMap<Manager, Models.ManagerSalesModels.Manager>();
            Mapper.CreateMap<Sale, Models.ManagerSalesModels.Sale>();

            Mapper.CreateMap<Models.ManagerSalesModels.Customer, Customer>();
            Mapper.CreateMap<Models.ManagerSalesModels.Product, Product>();
            Mapper.CreateMap<Models.ManagerSalesModels.Manager, Manager>();
            Mapper.CreateMap<Models.ManagerSalesModels.Sale, Sale>();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View("Sales",
                _saleHandler.GetAll().Select(Mapper.Map<Sale, Models.ManagerSalesModels.Sale>).ToList());
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult SaleGrid()
        {
            return View("SaleGrid", _saleHandler.GetAll().Select(Mapper.Map<Sale, Models.ManagerSalesModels.Sale>).ToList());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AddSale()
        {
            ViewBag.Products = Mapper.Map<IEnumerable<Product>, IEnumerable<Models.ManagerSalesModels.Product>>(
                _productHandler.GetAll()).Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                });
            ViewBag.Customers = Mapper.Map<IEnumerable<Customer>, IEnumerable<Models.ManagerSalesModels.Customer>>(
                _customerHandler.GetAll()).Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                });
            ViewBag.Managers = Mapper.Map<IEnumerable<Manager>, IEnumerable<Models.ManagerSalesModels.Manager>>(
                _managerHandler.GetAll()).Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.LastName
                });
            return View("AddSale", new Models.ManagerSalesModels.Sale());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddSale(Models.ManagerSalesModels.Sale sale)
        {
            try
            {
                _saleHandler.Add(Mapper.Map<Models.ManagerSalesModels.Sale, Sale>(sale));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                return View("AddSale", new Models.ManagerSalesModels.Sale());
            }

            return RedirectToAction("Index", "Sale");
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult EditSale(string id)
        {
            int value;
            int.TryParse(id, out value);
            var products =
                Mapper.Map<IEnumerable<Product>, IEnumerable<Models.ManagerSalesModels.Product>>(
                    _productHandler.GetAll()).Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    });
            var customers =
                Mapper.Map<IEnumerable<Customer>, IEnumerable<Models.ManagerSalesModels.Customer>>(
                    _customerHandler.GetAll()).Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    });
            var managers =
                Mapper.Map<IEnumerable<Manager>, IEnumerable<Models.ManagerSalesModels.Manager>>(
                    _managerHandler.GetAll()).Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.LastName
                    });

            ViewBag.Products = products;
            ViewBag.Customers = customers;
            ViewBag.Managers = managers;

            return View("EditSale", Mapper.Map<Sale, Models.ManagerSalesModels.Sale>(_saleHandler.GetItemById(value)));
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public ActionResult EditSale(Models.ManagerSalesModels.Sale sale)
        {
            try
            {
                _saleHandler.Update(Mapper.Map<Models.ManagerSalesModels.Sale, Sale>(sale));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                return View("EditSale", sale);
            }

            return RedirectToAction("Index", "Sale");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult RemoveSale(string id)
        {
            int value;
            int.TryParse(id, out value);

            _saleHandler.Remove(_saleHandler.GetItemById(value));

            return RedirectToAction("Index", "Sale");
        }
    }
}

ManagerSales-MVC/ManagerSales.Web.GUI/Views/Sale/AddSale.cshtml
@model ManagerSales.Web.GUI.Models.ManagerSalesModels.Sale

@{
    ViewBag.Title = "Add sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="~/Scripts/validate.config.js"></script>
<script src="~/Scripts/jquery.datetimepicker.full.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/jquery.datetimepicker.css" />

@using (Html.BeginForm("AddSale", "Sale", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "sale-form", @class = "form-horizontal", role = "form" }))
{
    <h2>Add sale</h2>
        <div class="form-group">
            @Html.LabelFor(m => m.Customer.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Customer.Id, (IEnumerable<SelectListItem>)ViewBag.Customers, new { @id = "customer", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Customer.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Manager.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Manager.Id, (IEnumerable<SelectListItem>)ViewBag.Managers, new { @id = "manager", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Manager.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Product.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Product.Id, (IEnumerable<SelectListItem>)ViewBag.Products, new { @id = "manager", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Product.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Summ, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Summ, new { @id = "summ", @class = "form-control", @placeholder = "summ" })
                @Html.ValidationMessageFor(m => m.Summ, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Date, new { @class = "form-control", @placeholder = "Login", id = "datetimepicker" })
                @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
}


<script>
    $(document).ready(function () {
        $('#datetimepicker').datetimepicker();
    });
</script>

ManagerSales-MVC/ManagerSales.Web.GUI/Views/Sale/EditSale.cshtml
@model ManagerSales.Web.GUI.Models.ManagerSalesModels.Sale

@{
    ViewBag.Title = "Edit sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="~/Scripts/validate.config.js"></script>
<script src="~/Scripts/jquery.datetimepicker.full.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/jquery.datetimepicker.css" />


@using (Html.BeginForm("EditSale", "Sale", new {ReturnUrl = ViewBag.ReturnUrl}, FormMethod.Post, new { id = "sale-form", @class = "form-horizontal", role = "form"}))
{
        <h2>Edit sale</h2>
        @Html.HiddenFor(m => m.Id, new { @class = "sr-only" })
        <div class="form-group">
            @Html.LabelFor(m => m.Customer.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Customer.Id, (IEnumerable<SelectListItem>)ViewBag.Customers, new { @id = "customer", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Customer.Id, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Manager.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Manager.Id,(IEnumerable<SelectListItem>)ViewBag.Managers, new { @id = "manager", @class = "form-control"})
                @Html.ValidationMessageFor(m => m.Manager.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Product.Id, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.DropDownListFor(m => m.Product.Id, (IEnumerable<SelectListItem>)ViewBag.Products, new { @id = "manager", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Product.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Summ, new {@class = "sr-only"})
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Summ, new {@id = "login", @class = "form-control", @placeholder = "Login"})
                @Html.ValidationMessageFor(m => m.Summ, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date, new { @class = "sr-only" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Date, new { @class = "form-control", @placeholder = "Login", id = "datetimepicker" })
                @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
}


<script>
    $(document).ready(function () {
        $('#datetimepicker').datetimepicker();
    });
</script>

ManagerSales-MVC/ManagerSales.Web.GUI/Views/Sale/SaleGrid.cshtml
@model IEnumerable<ManagerSales.Web.GUI.Models.ManagerSalesModels.Sale>
@{
    Layout = null;
}
@using GridMvc.Html
@if (User.IsInRole("Admin"))
{
    <button id="add" type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-plus"></span><a href="@Url.Action("AddSale","Sale")">Add</a>
    </button>
    @helper CustomRenderingOfColumn(ManagerSales.Web.GUI.Models.ManagerSalesModels.Sale order)
    {
        <div class="btn-group" style="margin: 0;">
            <a class="btn btn-default" href="/Sale/EditSale?id=@order.Id">Edit</a>
            <a class="btn btn-default" href="/Sale/RemoveSale?id=@order.Id">Delete</a>
        </div>
    }

    @Html.Grid(Model).Named("grid").Columns(columns =>
    {
        columns.Add(c => c.Date).Titled("Date").Filterable(true);
        columns.Add(c => c.Manager.LastName).Titled("Manager").Filterable(true);
        columns.Add(c => c.Customer.Name).Titled("customer").Filterable(true);
        columns.Add(c => c.Product.Name).Titled("Product").Filterable(true);
        columns.Add(c => c.Summ).Titled("Summ").Filterable(true);
        columns.Add()
            .Titled("Action")
            .Encoded(false)
            .Sanitized(false)
            .RenderValueAs(o => CustomRenderingOfColumn(o));
    }).Sortable(true).WithPaging(10)
}
else
{
    @Html.Grid(Model).Named("grid").Columns(columns =>
    {
        columns.Add(c => c.Id).Titled("Id").Filterable(true);
        columns.Add(c => c.Date).Titled("Date").Filterable(true);
        columns.Add(c => c.Manager.LastName).Titled("Manager").Filterable(true);
        columns.Add(c => c.Customer.Name).Titled("customer").Filterable(true);
        columns.Add(c => c.Product.Name).Titled("Product").Filterable(true);
        columns.Add(c => c.Summ).Titled("Summ").Filterable(true);
    }).Sortable(true).WithPaging(10)
}

ManagerSales-MVC/ManagerSales.Web.GUI/Views/Sale/Sales.cshtml
@model IEnumerable<ManagerSales.Web.GUI.Models.ManagerSalesModels.Sale>
@{
    ViewBag.Title = "Sales grid";
}

<h1>Sales</h1>
<button id="show" type="button" class="btn btn-default">Show Grafic</button>
<button style="display: none" id="hide" type="button" class="btn btn-default">Hide</button>
<div id="res" style="display: none">
    <div id="container" style="width: 100%; height: 400px;"></div>
    <div id="container2" style="width: 100%; height: 400px;"></div>
</div>
<div id="table" >
    @{
        Html.RenderAction("SaleGrid", "Sale");
    }
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script>
    $(document).ready(function() {
        function chart(data) {
            $('#container').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Managers'
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'The percent of sold products'
                    }

                },
                legend: {
                    enabled: false
                },
                series: data
            });
        }

        function chart2(data) {
            $('#container2').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: 'Sold products'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: false
                        },
                        showInLegend: true
                    }
                },
                series: data
            });
        }

        $("#refresh").click(function() {
            $.ajax({
                url: '@Url.Action("SaleGrid", "Sale")',
                type: 'Get',
                success: function(response) {
                    $("#table").replaceWith(response);
                },
                async: true,
                processData: false
            });
        });
 

    function getCharts() {
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("GetJsonForProductGraphic", "Graphic")',
            data: "{}",
            dataType: "json",
            success: function(Result) {
                chart(Result);
                console.log(Result);
            },
            error: function(Result) {
                alert("Error");
            }
        });
    }

    function getCharts2() {
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("GetJsonForManagerGraphic", "Graphic")',
                    data: "{}",
                    dataType: "json",
                    success: function (Result2) {
                        chart2(Result2);
                        console.log(Result2);
                    },
                    error: function (Result2) {
                        alert("Error");
                    }
                });
        }

        $("#show").click(function () {
            getCharts();
            getCharts2();
            $("#hide").show();
            $("#show").hide();
            $("#res").show();
            $("#table").hide();
        });
        $("#hide").click(function () {
            $("#show").show();
            $("#hide").hide();
            $("#res").hide();
            $("#table").show();
        });
    });
</script>